language: android

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email: false

sudo: false

before_install:
 - chmod +x gradlew

script:
 - chmod +x ./gradlew build connectedCheck

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/