language: android

env:
  global:
    - ANDROID_TARGET=android-27
    - ANDROID_ABI=x64

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.2
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-x64-android-27

  licenses:
    - '.+'

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email: false

sudo: false

before_install:
- yes | sdkmanager "platforms;android-27"

before_script:
  - chmod +x gradlew

script:
  - android list targets
  - echo no | android create avd --force -n test -t android-27 --abi x64 -no-accel
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
  - ./gradlew installDebug

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/